---
title: "Exam - Clean Data: Group 03"
format:
  html:
    embed-resources: true
editor: visual
author: Mei Lin Verghese Law Kung Sam(s194685), Thelma Urena(s242552), Alejandra Caballero(s231912),Marco Bonafede(s243247), Carlos Sainz(s253695)
execute:
  warning: false
---

## Load Libraries

```{r}
library(tidyverse)
```

## Running Code

```{r}
#| label: clean-data
#| eval: true

library(dplyr)
library(tibble)

gds_clean <- Table(gds) |>   # extract the expression table
  as_tibble()

```

```{r}
library(tibble)
library(readr)

expr_clean <- exprs_data |>
  as_tibble(rownames = "probe_id")

pheno_clean <- as_tibble(pheno_data, rownames = "sample_id")
write_tsv(pheno_clean, "data/02_gse54514_pheno.tsv.gz")

feature_clean <- as_tibble(feature_data, rownames = "probe_id")
write_tsv(feature_clean, "data/02_gse54514_annotation.tsv.gz")

readr::write_tsv(expr_clean,
                 file = "data/02_gse54514_expression.tsv.gz")


```

# Clean Platform table

```{r}
directory = getwd()
if (str_sub(directory,-1) == 'R'){
  directory = str_sub(directory,1,-3)
}
directory

platform_table = read_tsv(file.path(directory,'data/platform_table.tsv'))

platform_table_clean <- tibble(ID = platform_table$ID,
                               ILMN_Gene = platform_table$ILMN_Gene)

platform_table_clean <- platform_table_clean |> rename('Gene_ID' = ILMN_Gene)
platform_table_clean <- platform_table_clean |> rename('ILMN_Gene' = ID)

#gene_list = c('MAPK1','LFT','SOCS1','RELB','GNB4','B2M','IRAK4','WIPF1','CD8A','CD2','ELK1','CD3E','TRIM44','UGT2B7','TCP1','ORC1L','NEK1')
#platform_table_clean <- platform_table_clean |> filter(Gene_ID %in% gene_list)

write_tsv(x = platform_table_clean, 
          file = file.path(directory,'data/platform_table_clean.tsv'))
```
